### ISSUE TITLE
Image inline size override

### ISSUE THREAD

**Issue by trizonia** [andjosh/naked-wordpress#7]
Hie there,
The inline image size gets overridden by this css code:
```css
article .the-content img {
    width: 100%;
}
```
with the end effect of having huge images covering the entire article area.
I know I could simply delete the code, but I'm using a child theme and would prefer to keep the original code intact.
I've tried this:
```css
article .the-content img {
    width: auto;
}
```
but this still overrides the inline width and height code.
